resources:
- mmartofe-wally-secret.yaml
- deployment.yaml
- service.yaml
- route.yaml
configMapGenerator:
- name: www-files
  files:
  - index.html
commonLabels:
  app.kubernetes.io/part-of: taxi
  app.kubernetes.io/name: taxi
